const BUGSNAG_API_KEY = "6b60ca38eed1f7b8a306bf989a3d66af";
const BUGSNAG_RELEASE_STAGE = "development";

exports.BUGSNAG_API_KEY = BUGSNAG_API_KEY;
exports.BUGSNAG_RELEASE_STAGE = BUGSNAG_RELEASE_STAGE;
